import { type ImgCard, type MsgCard } from "@/types/interface/card";
import { type UserComment } from "@/types/interface/user";
// 卡片标签列表
export const msgLabel: string[] = [
  "全部",
  "目标",
  "理想",
  "过去",
  "未来",
  "爱情",
  "亲情",
  "友情",
  "秘密",
  "抽象",
  "其他",
];

// 图像标签列表
export const imgLabel: string[] = [
  "全部",
  "动漫",
  "设计",
  "娱乐",
  "综合",
  "自然",
  "景点",
  "人物",
  "机械",
  "文化",
  "其他",
];

// 卡片颜色列表
export const cardColorList = [
  "#fcafa24d",
  "#c7f58c79",
  "#bfefff",
  "#88c1f4c1",
  "#f7a4d3e1",
  "#fff6bba3",
  "#adffde89",
  "#f2dffad0",
];

export const cardNormal: MsgCard = {
  id: "",
  date: "2025.04.01",
  username: "",
  content: "",
  liked: false,
  likeCount: 0,
  type: "msg",
  commentCount: 0,
  color: cardColorList[0],
  label: msgLabel[0],
};

export let imageCardList: ImgCard[] = [
  {
    id: "198",
    label: msgLabel[0],
    likeCount: 0,
    liked: false,
    commentCount: 4,
    type: "img",
    url: "https://fastly.picsum.photos/id/950/800/600.jpg?hmac=VCWz8OFSt4IipU4c8yejk0ytSYDvI9IQzZLXmFCFTSg",
  },
  {
    id: "735",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 2,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/869/800/700.jpg?hmac=pyYQK163qKXljOD3IywNDsR1R3uK3H8pHrdMr4J_3qs",
  },
  {
    id: "996",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 3,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/865/800/800.jpg?hmac=JgPFAYsmz-9KM9lrMNRuGYkRy9vrjXLZfuvOPzst86k",
  },
  {
    id: "101",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 2,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/870/800/900.jpg?hmac=EQs65AlUsCYPHfo7orCDNzgqESwYzzXItQPIsAE15no",
  },
  {
    id: "255",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 1,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/169/800/500.jpg?hmac=gaW1bbFB0hXIH00pJ7HlckmxpYI8b8wr6BlmOyovVGQ",
  },
  {
    id: "344",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 5,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/945/800/700.jpg?hmac=jUZm7h62pzI0Nic8VBKYn9iKNDw9OrHPde9RWh5tLGk",
  },
  {
    id: "804",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 4,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/618/800/600.jpg?hmac=nF4ly6Yr4kvRPVSEyFdlQxhOTOijyuxMAxYuGG0vTAU",
  },
  {
    id: "460",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 2,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/640/800/800.jpg?hmac=5QyyvPx17ZEkWXyWKERk1jG1PlXhmwwU-HD61qPenlk",
  },
  {
    id: "928",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 1,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/41/800/900.jpg?hmac=N647pSyU39V9xSjVe5czbVzbxGIKCT5dAsi9Cb0Uq18",
  },
  {
    id: "51",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 2,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/997/800/500.jpg?hmac=sQGfMT5Suv-oRTV2xUNA7ZyQRQizQWTPoNgo2IPuciA",
  },
  {
    id: "646",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 3,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/496/800/600.jpg?hmac=B85q2nwl3I2GVAwtQzVONr7mCKA9btg-_Xo35SzDjgM",
  },
  {
    id: "879",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 4,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/248/800/800.jpg?hmac=AnUJHut6UxpJc0cVVeeA3PlRPCksMrh_Kqt1bPcPPsE",
  },
  {
    id: "144",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 5,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/943/800/700.jpg?hmac=lKugSTDXYywQYFa8HEGKxajcMxZE2QcxUV7KufUV_pI",
  },
  {
    id: "810",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 6,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/929/800/900.jpg?hmac=N5ekGhsxoTWKAM2cb8MiDcOUlWSxrMxXZ-58Kjs16HE",
  },
  {
    id: "287",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 7,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/41/800/500.jpg?hmac=GDuBhfyk4hfBd8Mt7-HC3ZKC2AiGnRt0law9B3ClWn4",
  },
  {
    id: "863",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 8,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/232/800/600.jpg?hmac=xmfXvGa03AJEm275MAtd3loQndYtexnUuXExS4zOIvs",
  },
  {
    id: "334",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 1,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/358/800/700.jpg?hmac=2Wl-ZWzrTyhFp5QgJU3NByu04HbS2NWUsZMjgE46aZE",
  },
  {
    id: "335",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 21,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/156/800/800.jpg?hmac=Zmsl_BXhufelcy3t3uekDFTKHhUv_21pQDnh6oAb5Ec",
  },
  {
    id: "336",
    label: msgLabel[0],
    likeCount: 0,
    commentCount: 13,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/558/800/900.jpg?hmac=CeZ--arRkYHbFyvmItlzDiu6x7hpB9WeOq3N31E0lks",
  },
];
