import { Label, imgLabel } from "@/types/enum/label";
import { type ImgCard, type MsgCard } from "@/types/interface/card";
import { type userComment } from "@/types/interface/user";
// 卡片标签列表
export const cardLabelList: Label[] = [
  Label.ALL,
  Label.TARGET,
  Label.IDEAL,
  Label.PAST,
  Label.FUTURE,
  Label.LOVE,
  Label.LOVELETTER,
  Label.FRIEND,
  Label.SECRET,
  Label.ABSTRUCT,
  Label.OTHER,
];
// 图像标签列表
export const imgLabelList: imgLabel[] = [
  imgLabel.ALL,
  imgLabel.ANIME,
  imgLabel.DESIGN,
  imgLabel.ENTERTAINMENT,
  imgLabel.OVERALL,
  imgLabel.NATURAL,
  imgLabel.SCENIC,
  imgLabel.PERSON,
  imgLabel.MECHANICAL,
  imgLabel.CULTURE,
];
// 卡片颜色列表
export const cardColorList = [
  "#fcafa24d",
  "#c7f58c79",
  "#bfefff",
  "#88c1f4c1",
  "#f7a4d3e1",
  "#fff6bba3",
  "#adffde89",
  "#f2dffad0",
];

export const cardNormal: MsgCard = {
  id: "",
  date: "2025.04.01",
  username: "",
  message: "",
  liked: false,
  likeCount: 0,
  type: "msg",
  commentCount: 0,
  color: cardColorList[0],
  label: cardLabelList[1],
};
("https://picsum.photos/id/800/900");
// 评论列表
export const userComments: userComment[] = [
  {
    id: "101",
    img: "https://picsum.photos/40/40",
    name: "jvantuyl",
    date: "2021-01-01 11:19",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam tincidunt, nunc nisl aliquet nisl,eu aliquam nisl nunc eu nisl.",
  },
  {
    id: "102",
    img: "https://picsum.photos/40/40",
    name: "BrianTheCoder",
    date: "2021-01-01 11:19",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam tincidunt, nunc nisl aliquet nisl,eu aliquamnisl nunc eu nisl.",
  },
  {
    id: "103",
    img: "https://picsum.photos/40/40",
    name: "John Doe",
    date: "2021-01-01 11:19",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam tincidunt, nunc nisl aliquet nisl,eu aliquam nisl nunc eu nisl.",
  },
  {
    id: "104",
    img: "https://picsum.photos/40/40",
    name: "Jane Doe",
    date: "2021-01-01 11:19",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam tincidunt, nunc nisl aliquet nisl,eu aliquam nisl nunc eu nisl.",
  },
  {
    id: "105",
    img: "https://picsum.photos/40/40",
    name: "jvantuyl",
    date: "2021-01-01 11:19",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam tincidunt, nunc nisl aliquet nisl,eu aliquam nisl nunc eu nisl.",
  },
  {
    id: "106",
    img: "https://picsum.photos/40/40",
    name: "BrianTheCoder",
    date: "2021-01-01 11:19",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam tincidunt, nunc nisl aliquet nisl,eu aliquamnisl nunc eu nisl.",
  },
  {
    id: "107",
    img: "https://picsum.photos/40/40",
    name: "John Doe",
    date: "2021-01-01 11:19",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam tincidunt, nunc nisl aliquet nisl,eu aliquam nisl nunc eu nisl.",
  },
  {
    id: "108",
    img: "https://picsum.photos/40/40",
    name: "Jane Doe",
    date: "2021-01-01 11:19",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam tincidunt, nunc nisl aliquet nisl,eu aliquam nisl nunc eu nisl.",
  },
];

// export let imageCardList = [
//   {
//     id: "1",
//     label: "目标",
//     likeCount: 0,
//     liked: false,
//     url: "https://java-web-lws.oss-cn-beijing.aliyuncs.com/001.jpg",
//   },
//   {
//     id: "2",
//     label: "目标",
//     likeCount: 0,
//     liked: false,
//     url: "https://java-web-lws.oss-cn-beijing.aliyuncs.com/c1b9ac46-acab-4e63-a371-43d20706e3b1.jpg",
//   },
//   {
//     id: "3",
//     label: "目标",
//     likeCount: 0,
//     liked: false,
//     url: "https://java-web-lws.oss-cn-beijing.aliyuncs.com/2025/01/76497599-f2a1-4d0b-817f-4ad7d2154420.jpg",
//   },
//   {
//     id: "4",
//     label: "目标",
//     likeCount: 0,
//     liked: false,
//     url: "https://java-web-lws.oss-cn-beijing.aliyuncs.com/2025/01/7cc65270-c8da-485f-b14c-618de60365b4.png",
//   },
//   {
//     id: "5",
//     label: "目标",
//     likeCount: 0,
//     liked: false,
//     url: "https://java-web-lws.oss-cn-beijing.aliyuncs.com/2025/02/6cba1150-b89e-46e0-a66e-936cc2760f58.jpg",
//   },
//   {
//     id: "6",
//     label: "目标",
//     likeCount: 0,
//     liked: false,
//     url: "https://java-web-lws.oss-cn-beijing.aliyuncs.com/2025/02/8220d2b9-5bbf-45ce-856b-c5c7e2c11f2a.jpeg",
//   },
//   {
//     id: "7",
//     label: "目标",
//     likeCount: 0,
//     liked: false,
//     url: "https://java-web-lws.oss-cn-beijing.aliyuncs.com/2025/02/c2813a27-0a9c-4319-b023-302192f8feac.png",
//   },
// ];

export let imageCardList: ImgCard[] = [
  {
    id: "198",
    label: "动漫",
    likeCount: 0,
    liked: false,
    commentCount: 0,
    type: "img",
    url: "https://fastly.picsum.photos/id/950/800/600.jpg?hmac=VCWz8OFSt4IipU4c8yejk0ytSYDvI9IQzZLXmFCFTSg",
  },
  {
    id: "735",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/869/800/700.jpg?hmac=pyYQK163qKXljOD3IywNDsR1R3uK3H8pHrdMr4J_3qs",
  },
  {
    id: "996",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/865/800/800.jpg?hmac=JgPFAYsmz-9KM9lrMNRuGYkRy9vrjXLZfuvOPzst86k",
  },
  {
    id: "101",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/870/800/900.jpg?hmac=EQs65AlUsCYPHfo7orCDNzgqESwYzzXItQPIsAE15no",
  },
  {
    id: "255",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/169/800/500.jpg?hmac=gaW1bbFB0hXIH00pJ7HlckmxpYI8b8wr6BlmOyovVGQ",
  },
  {
    id: "344",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/945/800/700.jpg?hmac=jUZm7h62pzI0Nic8VBKYn9iKNDw9OrHPde9RWh5tLGk",
  },
  {
    id: "804",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/618/800/600.jpg?hmac=nF4ly6Yr4kvRPVSEyFdlQxhOTOijyuxMAxYuGG0vTAU",
  },
  {
    id: "460",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/640/800/800.jpg?hmac=5QyyvPx17ZEkWXyWKERk1jG1PlXhmwwU-HD61qPenlk",
  },
  {
    id: "928",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/41/800/900.jpg?hmac=N647pSyU39V9xSjVe5czbVzbxGIKCT5dAsi9Cb0Uq18",
  },
  {
    id: "51",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/997/800/500.jpg?hmac=sQGfMT5Suv-oRTV2xUNA7ZyQRQizQWTPoNgo2IPuciA",
  },
  {
    id: "646",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/496/800/600.jpg?hmac=B85q2nwl3I2GVAwtQzVONr7mCKA9btg-_Xo35SzDjgM",
  },
  {
    id: "879",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/248/800/800.jpg?hmac=AnUJHut6UxpJc0cVVeeA3PlRPCksMrh_Kqt1bPcPPsE",
  },
  {
    id: "144",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/943/800/700.jpg?hmac=lKugSTDXYywQYFa8HEGKxajcMxZE2QcxUV7KufUV_pI",
  },
  {
    id: "810",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/929/800/900.jpg?hmac=N5ekGhsxoTWKAM2cb8MiDcOUlWSxrMxXZ-58Kjs16HE",
  },
  {
    id: "287",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/41/800/500.jpg?hmac=GDuBhfyk4hfBd8Mt7-HC3ZKC2AiGnRt0law9B3ClWn4",
  },
  {
    id: "863",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/232/800/600.jpg?hmac=xmfXvGa03AJEm275MAtd3loQndYtexnUuXExS4zOIvs",
  },
  {
    id: "334",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/358/800/700.jpg?hmac=2Wl-ZWzrTyhFp5QgJU3NByu04HbS2NWUsZMjgE46aZE",
  },
  {
    id: "335",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/156/800/800.jpg?hmac=Zmsl_BXhufelcy3t3uekDFTKHhUv_21pQDnh6oAb5Ec",
  },
  {
    id: "336",
    label: "动漫",
    likeCount: 0,
    commentCount: 0,
    type: "img",
    liked: false,
    url: "https://fastly.picsum.photos/id/558/800/900.jpg?hmac=CeZ--arRkYHbFyvmItlzDiu6x7hpB9WeOq3N31E0lks",
  },
];
