<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>comment.wall</groupId>
  <artifactId>java-comment-wall</artifactId>
  <version>1.0-SNAPSHOT</version>

  <packaging>pom</packaging>
  <name>Archetype - java-comment-wall</name>
  <url>http://maven.apache.org</url>
  <modules>
    <module>comment-wall-pojo</module>
    <module>comment-wall-common</module>
    <module>comment-wall-service</module>
  </modules>
    <properties>
        <mybatis.plus.version>3.5.7</mybatis.plus.version>
        <org.projectlombok.version>1.18.20</org.projectlombok.version>
        <lombok.version>1.18.20</lombok.version>
        <knife4j>4.4.0</knife4j>
        <mysql.version>8.0.32</mysql.version>
        <hutool>5.8.20</hutool>
    </properties>
  <dependencies>
      <!-- mysql -->
      <dependency>
          <groupId>mysql</groupId>
          <artifactId>mysql-connector-java</artifactId>
          <version>${mysql.version}</version>
          <scope>runtime</scope>
      </dependency>
      <!-- mybatis-plus -->
      <dependency>
          <groupId>com.baomidou</groupId>
          <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
          <version>${mybatis.plus.version}</version>
      </dependency>
    <!-- lombok -->
    <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>1.18.24</version>
    </dependency>
      <!--Hutool工具包-->
      <dependency>
          <groupId>cn.hutool</groupId>
          <artifactId>hutool-all</artifactId>
          <version>5.8.11</version>
      </dependency>
      <!-- swagger -->
      <dependency>
          <groupId>com.github.xiaoymin</groupId>
          <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
          <version>${knife4j}</version>
      </dependency>
</dependencies>

</project>
